# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:$RUBY_VERSION-slim

# Ensure binding is always 0.0.0.0
# Binds the server to all IP addresses of the container, so it can be accessed from outside the container.
ENV BINDING="0.0.0.0"
# Enable frozen string literal for performance
ENV RUBYOPT="--enable-frozen-string-literal"

# Rails app lives here
WORKDIR /workspaces/rails-docker-boilerplate

# Install packages needed to build gems
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential git libpq-dev libyaml-dev pkg-config && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives
